title: 拾趣，志人
subtitle: 白水日常需拾趣，书迹学知尤志人
description: 白水日常需拾趣，书迹学知尤志人
keywords: null
author: awesome-wind
language: zh-CN
timezone: Asia/Shanghai
url: https://theme-next.js.org
root: /
permalink: /blog/:year/:month/:title.html
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render:
  - robots.txt
  - animate/*
  - highlight/*
new_post_name: ':year-:month-:day-:title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
archive_generator:
  per_page: 12
  yearly: true
  monthly: true
  daily: false
tag_generator:
  per_page: 20
category_generator:
  per_page: 20

default_category: uncategorized
category_map: 
tag_map: 

date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: next
marked:
  smartypants: false
  lazyload: true
search:
  path: search.json
  field: all
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
deploy:
  type: git
  repository: https://github.com/awesome-wind/awesome-wind.github.io.git
  branch: main
  token: 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
